### ISSUE TITLE
4 Icons are using Stroke instead of Fill (Incorrectly Viewing Icons)

### ISSUE THREAD

**Issue by Ferynix** [zaydek/heroicons.dev#1]
I noticed 4 of the icons in the list have an issue:

`currency-dollar`, `moon`, `phone` and `ticket`

they look thick and bulky compared to all the other icons, and when you hover over them, you can see that they are actually using STROKE instead of FILL.. (I think)

which is probably what is causing them to be all fat and bulky, see here:

Hovering on ticket:

Broken ticket icon versus a working translate icon to the right:

![Capture](https://user-images.githubusercontent.com/44554976/75599492-61657780-5a73-11ea-8388-d11f574fd4b2.PNG)

Not hovering:

![Capture](https://user-images.githubusercontent.com/44554976/75599485-4b57b700-5a73-11ea-9542-b7372303474e.PNG)

You can very well see the difference. the other 3 icons besides ticket also have this problem

**Comment by zaydek** [comment]
Oh. Interesting. I noticed this too but wasn’t sure what the root cause is. Your analysis makes sense. I’ll do some work on the icon viewer soon and attempt to solve for this. Thank you!

**Comment by zaydek** [comment]
OK so I went ahead and did two things:

1. [I created an issue on the official repository](https://github.com/refactoringui/heroicons/issues/11#issue-573412745); from what I can tell I can’t easily fix this without access to the source files
2. I added a warning symbol on the viewer for the meantime

I hope that helps!

**Comment by Ferynix** [comment]
Alright, this is an out-of-repository issue, I shall close it, thanks for the input
