### ISSUE TITLE
[Question] Zondicons...?

### ISSUE THREAD

**Issue by telkins** [zaydek/heroicons.dev#15]
I know this is called **hero**icons.dev, but is there any chance of pulling in Schoger's zondicons collection as well?

I'm open to helping out, but I'd rather not put in the effort if it's not going to be considered/possible or if (it's known that) someone's already working on it.

Thanks...!  :-)

**Comment by zaydek** [comment]
Hey @telkins, thanks for creating an issue!

We can definitely add Zondicons. From what I gather there are roughly 270 Zondicons total but are no longer under development. Are developers using Zondicons? Do you mind pointing out any real-world examples?

I saw that you were behind the effort to get Zondicons added to Blade Icons, thanks for following up here as well!

**Comment by codex-zaydek** [comment]
While we’re at it, we minus well gather what other popular open source icon libraries are available. Feather Icons comes to mind for one. I’m curious about making heroicons.dev a _general open source icon viewer_. I’m not sure this has been done before. I also think heroicons.dev isn’t a bad domain to bundle other icons under. Especially if all non-Heroicons are lazily loaded.

**Comment by telkins** [comment]
Hi @codex-zaydek ,

Thanks for the quick response.  Sorry for taking some time to get back to you.  Busy weekend.  :-)

I'm not 100% sure of the status of zondicons with regards to development.  I do believe it's used by developers beside me, as you may be aware considering your knowledge of the Blade Icons package.  I'm currently using them both (via the aforementioned package) in a kind of hobby site: https://immadb.com.  As for other real-world examples, I couldn't point to any.  Fwiw, I couldn't point to any other real-world examples of developers using heroicons, either.  :-)

Anyway, I have used https://react-icons.netlify.com in the past and thought it was nice, but preferred your site since the Tailwind guys recommend Heroicons...and I thought it would be nice to get Schoger's other icon collection at the same.

Let me know what your thoughts are, whether you have any more questions/concerns, and whether or not you need any help.

Thanks again.

**Comment by zaydek** [comment]
Thanks for following-up.

Yeah, I can add Zondicons as well as alternate syntax copy-paste support, such as for Blade Icons and more. Will probably be a couple of days from now. 👍

**Comment by zaydek** [comment]
Sorry I haven’t worked on heroicons.dev for a bit. When I have more time I will. Just wanted to update you. The most helpful thing at this point would be a PR to get the ball rolling.

**Comment by maxjendrall** [comment]
@telkins We are actually using them partly in production. :)
