### ISSUE TITLE
Add React copy paste

### ISSUE THREAD

**Issue by oeb25** [zaydek/heroicons.dev#18]
Hi there! An awesome tool you have built, I'm a big fan.

I'm using this with React and as such need `className` instead of `class`. Similarly with properties containing hyphen `-`, like `clip-rule` and `fill-rule`. So having a toggle for the alternate property names would be great!
I might go in a work out a PR tonight if I have time.

I'm not sure if this has overlap with #14 or not.

Not strictly related, but I'll just mention it here. Having an input where one could choose the desired copied size.

Thoughts on this? Also thanks for making this site, good job 👍

**Comment by zaydek** [comment]
Thanks! Yeah, love this. Do you have any proposals for the UI? That’s really the bottleneck for me to put out new features: How should it look? Wheres should it go? That kind of thing. 🙂

**Comment by zaydek** [comment]
By the web, Figma prototypes are totally welcome as far as UI goes.

**Comment by maxjendrall** [comment]
In what way do you need UI support?
I could contribute on that

**Comment by zaydek** [comment]
@toorusr Thank you! Implementing new features in JavaScript is relatively easy for me, but having a sense of how they should look and work, and how they should appear on the site, etc. helps me a lot.

One example is a Figma mockup of how React copy-paste should look. I can add a todo list of other ideas that will be easier for me to implement with designs in place.

**Comment by oeb25** [comment]
Had a quick go at it. I'm thinking either put it next to the two toggles that are already there (day/night, hollow/solid) or move the settings to a tab.

If more settings need to be added, such as the size of the copy, a more dedicated settings area that could be hidden might be nice.

Anyway, [heres my try](https://www.figma.com/file/5bQ7ifXp8m4HhNGfQVbJw3/Heroicons). I might try out some more stuff later.

**Comment by zaydek** [comment]
Thanks @oeb25. That really helps me organize my thought so I can add new features efficiently. I actually riffed on your version and made a new version here and added you as a contributor so you can directly edit it.

https://figma.com/file/6GcmJrF171ptS96FinXV58

My only concern with this approach is that we would have two pop-outs -- one for the initial menu, and one following `<select>`. Thoughts? Feel free to leave annotations in Figma as well.

**Comment by maxjendrall** [comment]
I know dropdowns are cool, but I like the style you have @oeb25 with a [slight difference](https://www.figma.com/file/WxcURu1Ds7QbcMngu7cPwe/Heroicons-Copy).

**Comment by zaydek** [comment]
> I know dropdowns are cool, but I like the style you have @oeb25 with a [slight difference](https://www.figma.com/file/WxcURu1Ds7QbcMngu7cPwe/Heroicons-Copy).

This is probably better because there’s less UI needed. The only thing this needs in my opinion is some kind of small notification in the corner explaining what you did, at least for the first trigger or so. This should be enough UI for me to follow-up soonish.

Really appreciate the collaboration! This is definitely the most useful way to help me.

**Comment by oeb25** [comment]
Yes, I agree. It would be simplest to just have it next to the others. My only concern is that if more settings get added (such as sizing), it would clutter up the input. But maybe that should be postponed to when that scenario actually occurs.

Both approaches look good to me, but I do see your concern with having dropdowns inside dropdowns. I tried changing the dropdowns to "radio buttons" if you will, I put it below yours, @codex-zaydek, in this [document](https://www.figma.com/file/6GcmJrF171ptS96FinXV58/Heroicons-(Copy)?node-id=9%3A2&viewport=358%2C247%2C0.43827682733535767).

**Comment by zaydek** [comment]
Hey guys, all of this looks great. I think I’ll probably need to use both because on mobile, the search bar gets too crammed (between actually typing text — that, or I could probably more simply remove the search icon on mobile?).

Anyway, I think there’s more than enough resources here for me to _make something!_ Really love this kind of help.

**Comment by maxjendrall** [comment]
Yeah, sure, then @codex-zaydek could, may be put the :dots-horizontal: at the end of the input when there is not enough space and the icons are displayed in the input like right now, if clicked.

And sizing is not needed because it's SVG ;) @oeb25

**Comment by oeb25** [comment]
Oh my point is not the size of the SVG @toorusr, but rather the class that is applied, that is adjusting the 8 in `class="w-8 h-8"`.

**Comment by maxjendrall** [comment]
Yeah sure, there could also be tailwindcss settings directly.
Right! :)

**Comment by attilah** [comment]
@codex-zaydek beside the UI, what would you think about a dual function search bar like in vs code. So for example I could enter: >output:react and >type:outline, whenever you hit > all the settings could pop up and could be filtered. It would make it handy.

Another similar addition of keyboard only copy could be a CMD + 1-9 key handler on the first 9 search result ;-) small 1-9 annotations could be in the icons' top-left corner as a visual queue.

**Comment by zaydek** [comment]
@attilah Hey there! I can’t say I like the first suggestion but shortcuts some sense. We could have command-1, -2, -3, etc. select the setting states, I like that.

When I merge the current pull request I can add your suggestion! Thank you.

**Comment by zaydek** [comment]
Sorry for the delay. This has now been implemented based on feedback from this issue. Thank you all for contributing!
