### ISSUE TITLE
Links are missing href="" (they're just blue text now)

### ISSUE THREAD

**Issue by Ferynix** [zaydek/heroicons.dev#2]
All the links in the page, and I mean all of them, are missing the href attribute which gives the anchor tag its ability to hyperlink to places.

These links are easily available, is this a bug? or were they just ignored?

![Capture](https://user-images.githubusercontent.com/44554976/75599528-b73a1f80-5a73-11ea-9c60-c5ce6afce455.PNG)

Missing attributes:

![Capture](https://user-images.githubusercontent.com/44554976/75599543-dcc72900-5a73-11ea-8a30-932095a766ee.PNG)

**Comment by zaydek** [comment]
Thanks for creating the issue. I wasn’t sure at the time how to handle this — JavaScript or HTML (for downloading or copying the SVG to the clipboard). Regardless, I’ll try and improve this experience soon.

Please keep the issues coming, it helps!

**Comment by zaydek** [comment]
Wanted to let you know I’ve fixed all links, including support for copying SVGs to the clipboard! Please let me know if it can be further improved!
