### ISSUE TITLE
Ads on heroicons

### ISSUE THREAD

**Issue by herpaderpaldent** [zaydek/heroicons.dev#20]
I noticed that you have enabled adds to your page and i have mixed feelings about this. 

![image](https://user-images.githubusercontent.com/6583519/79719896-d0c34f00-82df-11ea-9f7e-9a0bcae59981.png)

Would you consider github sponsorship f.e. instead of 'earning' money with ads?

**Comment by zaydek** [comment]
Hey there! thanks for noticing. Absolutely. Would you mind if I put a sponsor me on GitHub ad instead?

**Comment by zaydek** [comment]
I applied for GitHub Sponsors, so will need to wait for account approval.

**Comment by clnsdzy** [comment]
The ads are not all over the place so it's fine for me. First time using heroicons. Good work team! 👏

**Comment by zaydek** [comment]
I’m going to go ahead and keep ads for now because that’s working and I don’t think they’re overly annoying or distracting. Feel free to reopen this issue if you feel otherwise.

**Comment by zaydek** [comment]
Hey all, I wanted to announce that I’ve added support for _disabling ads_ on [heroicons.dev](https://heroicons.dev) by sponsoring me on GitHub!

[More info here](https://github.com/codex-zaydek/heroicons.dev#how-to-disable-ads-github-sponsors) if you’re curious.

Thanks @herpaderpaldent for originally opening the issue!
