### ISSUE TITLE
Press "/" to Focus is currently not working

### ISSUE THREAD

**Issue by aaronschweig** [zaydek/heroicons.dev#23]
Hello, thank you for your nice site!

I just tried to use the Press "/" to focus feature. Unfortunately it is not working for me (using a german keyboard). If you want, i can create a PR and provide a fix for it?

Again Thank you for the cool site 😊

**Comment by zaydek** [comment]
Oh, weird. Thanks for creating an issue @aaronschweig.

So the site uses `e.keyCode === 191` to catch that case. Can you tell me what you see on this site when you press forward-slash? https://keycode.info

**Comment by aaronschweig** [comment]
For me, it shows 55.

I guess this behaviour is caused by the KeyCode taking the position of the Key on the keyboard into account. Mayeb it would be easier to just use `event.key`. This should return "/" whenever this specific key is pressed.
<img width="1368" alt="Bildschirmfoto 2020-05-29 um 12 17 31" src="https://user-images.githubusercontent.com/42006873/83249110-620ec680-a1a6-11ea-9df4-ba114182b34f.png">

**Comment by zaydek** [comment]
Right. Thanks for following-up! So I can check for `e.key === "/"` first. Generally, I actually avoid comparing key data versus key codes because it can be less reliable for int.l input but this is one such edge case.

**Comment by aaronschweig** [comment]
Thank you! This would be great 👍 And thanks for sharing this hint with international Input 😉

**Comment by zaydek** [comment]
Added a fix for this — let me know if you have further issues.
