### ISSUE TITLE
[Bug] Clipboard failing on Safari 13

### ISSUE THREAD

**Issue by zaydek** [zaydek/heroicons.dev#3]
https://twitter.com/andarcy/status/1233932068062498818

**Comment by GeoffSelby** [comment]
This is failing on any browser that does not support the Clipboard API. I'm working on a fallback now to get around it using `execCommand()`.

Expect a PR tomorrow.

**Comment by zaydek** [comment]
@GeoffSelby in the meantime do you mind testing whether this technique works on mobile/Safari?

**Comment by GeoffSelby** [comment]
I can only test on iOS but it is working on the latest versions of Safari, Chrome, and Firefox for iOS. Older versions may have some issues so I'm adding a fallback for that as well.

**Comment by zaydek** [comment]
Awesome! Thank you so much. I’ll check this out in full soon.
