### ISSUE TITLE
include the key for the icon e.g "archive" "arrow-circle-up" in the copy svg markup ?

### ISSUE THREAD

**Issue by danjus10** [zaydek/heroicons.dev#33]
Hey. Love your work on the heroicons.dev site - super easy to copy paste the output 👍 

would it be possible to include the key for the icon e.g "archive" "arrow-circle-up" in the svg markup as an attribute.  that way my inline svg is easier to read & update .   thanks. 

`<svg fill="none" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24" stroke="currentColor"><path d="M5 8h14M5 8a2 2 0 110-4h14a2 2 0 110 4M5 8v10a2 2 0 002 2h10a2 2 0 002-2V8m-9 4h4" **key="archive"**></path></svg>`

**Comment by zaydek** [comment]
Hey there. I did add this in the remastered version of the site. For now I’m using `class="<icon-name> ..."` rather than `key="..."` but the same idea applies. Let me know if you had something else in mind. Will close this for now.
