### ISSUE TITLE
Add back support for light mode

### ISSUE THREAD

**Issue by zaydek** [zaydek/heroicons.dev#39]
Having all the dark and light mode classes together is a hassle. If we use higher-order styled header components (for text) this may be workable. Other alternatives are doing themes in CSS, but then we need IDs, classes, or attributes to hook into. Maybe we can use `data-dark="..."` as a pattern.

**Comment by iKlsR** [comment]
Came here to open this issue. See https://jessicaotis.com/academia/never-use-white-text-on-a-black-background-astygmatism-and-conference-slides/, dark mode is unusable for some people.

**Comment by zaydek** [comment]
Yeah, that’s a good point. For what it’s worth I actually never use hard white anywhere except for the ‘Heroicons’ title. In general, I always use a faded white or color to lower the high contrast ratio.

I’ll follow-up when I add back light mode! Thank you for sharing the article.

**Comment by zaydek** [comment]
(Note to self)

Can use the following pattern to implement maintainable themes / dark mode:

```js
const Apply = ({ className, children }) => (
  React.cloneElement(children, {
    ...children.props,
    className: className +  (!children.props.className ? "" : " " + children.props.className),
  })
)

<Apply className="<string>">
  <Apply className={/* Can be expression */}>
    <Apply className="<string>">
      {/* You code here */}
    </Apply>
  </Apply>
</Apply>
```

The cool thing about this is we don’t need to use a plugin to manage dark mode; we can just use a `<DarkMode>`.

For example:

```js
<LightMode className="..." style={{ /* ... */ }}>
  <DarkMode className="..." style={{ /* ... */ }}>
    {/* ... */}
  <DarkMode>
</LightMode>
```

**Comment by zaydek** [comment]
Shipping this to production very soon.
