### ISSUE TITLE
Size classes inside the pasted svg ???

### ISSUE THREAD

**Issue by sylann** [zaydek/heroicons.dev#45]
Hi there.

I've been using your excellent app for a project I'm currently working on.
Until recently, pasted svgs had no classes and especially no size classes which was ideal for my case.

But it seems svgs now come with a fixed size of w-6 h-6 and since I don't want that, I 'm now forced to remove them manually.

I can't imagine everyone wants the icons to be precisely 24px.
Is there a reason for adding this size?

**Comment by zaydek** [comment]
Hey there! Thanks for opening this issue.

You make a really good point. The reasoning was that some some people have requested this feature, while others want the opposite. Personally, I think it’s better to include classes so users have something to work with, but I can understand how that can be easily just as annoying.

I think I can add a gear icon somewhere on the search bar that opens a modal that allows me to give devs a lot more control about their exported icons (and save those settings to localStorage).

To start, we can add support for:

- [ ] Customizing the class string
- [ ] Enable attributing the icon name (in the class or as an attribute)
- [ ] Enable visually centering icons #31
- [ ] Enable import syntax, with support for customizing the import string e.g. `import { ...} from heroicons`

But to start I can focus on ‘Customizing the class string’ and syncing to localStorage.

**Comment by sylann** [comment]
Hey @codex-zaydek ,

Thanks for the quick reply.
This looks like a very good idea.

I would happily propose my help but sadly I really don't have much time these days.

**Comment by zaydek** [comment]
Don’t worry — after implementing light mode this will be at the top of my radar. Thank you for opening the original issue!

**Comment by zaydek** [comment]
So I decided to keep the `w-6 h-6` classes for now because if you don’t have them, the icons are invisible. We can review this at a later time, but for now I want to push the new version to production.
