### ISSUE TITLE
Scan QRCode Icon

### ISSUE THREAD

**Issue by hsul4n** [zaydek/heroicons.dev#56]

**Comment by zaydek** [comment]
Hey @hsul4n — what does this issue mean? If I‘m not mistaken, the QRCode is available as ‘qrcode’. Is there another icon that’s missing?

Thanks!

**Comment by hsul4n** [comment]
> Hey @hsul4n — what does this issue mean? If I‘m not mistaken, the QRCode is available as ‘qrcode’. Is there another icon that’s missing?
> 
> 
> 
> Thanks!

I mean the same icon in material design [qr_code_scanner](https://material.io/resources/icons/?icon=qr_code_scanner&style=baseline).

**Comment by zaydek** [comment]
Did you mean you want to add support for Material Design icons? Sorry, just a bit confused. 🤔

**Comment by hsul4n** [comment]
> Did you mean you want to add support for Material Design icons? Sorry, just a bit confused. 🤔

I'm trying to explain that we need to add a new icon for `qrcode_scan` the same one available in Material Design icons.

**Comment by zaydek** [comment]
OH! You can request icons here: https://github.com/tailwindlabs/heroicons/issues.

Sorry about that!

**Comment by hsul4n** [comment]
OH! looks like this repo for website only 😅
