### ISSUE TITLE
Include XML Namespace xmlns

### ISSUE THREAD

**Issue by ezra-works** [zaydek/heroicons.dev#59]
While copying icons as JSX or HTML it does not contain the xmlns attribute in the svg tag. Can you please include it or should I be adding it globally somewhere ? 

**copy to clipboard results** 
`<svg viewBox="0 0 20 20" fill="currentColor" className="search"><path fillRule="evenodd" d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z" clipRule="evenodd" /></svg>`

**expected** 
`<svg xmlns="http://www.w3.org/2000/svg"  viewBox="0 0 20 20" fill="currentColor" className="search"><path fillRule="evenodd" d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z" clipRule="evenodd" /></svg>`

**Comment by zaydek** [comment]
Sure thing. Will fix this shortly.

**Comment by zaydek** [comment]
Implemented in development. Will push to prod soon. Thank you for opening the issue!

**Comment by zaydek** [comment]
@ezra-moses This is now implemented based on your feedback. Let me know if you have further feedback.
