### ISSUE TITLE
Persistent settings

### ISSUE THREAD

**Issue by O4epegb** [zaydek/heroicons.dev#61]
Would be nice to have persistent settings (`copy as` and `icon style`), so you would not need to select them every time you load the app.

Could try to do it myself but I see that some sort of refactoring is going on :)

**Comment by zaydek** [comment]
Thanks for creating an issue! I will follow-up / close this when I implement this feature.

You bet! Will add very soon. 😉 (Huge refactor)

**Comment by zaydek** [comment]
@O4epegb Hey again. This is now implemented in my localhost development version. I will push to production shortly!

**Comment by zaydek** [comment]
@O4epegb Now live! Let me know if you have further feedback.

**Comment by O4epegb** [comment]
Great work, thank you!
