### ISSUE TITLE
Add a hint that searching "new" will show only "new icons"

### ISSUE THREAD

**Issue by oliverpool** [zaydek/heroicons.dev#78]
First of all, thank you very much for this great resource !

---

I was looking for a newsletter icon and was surprised with the search results:
-  `ne` returned 2 results
-  `new` returned no result
-  `news` returned 2 results (the same as `ne`)

It turns out that this is a feature to discover the new icons.

It would be great to add an hint (when "new" is searched) that the results are only the new icons.

**Comment by zaydek** [comment]
Sorry for the late (super late!) reply. Search has been updated to use a simpler, more [flexible algorithm](https://github.com/zaydek/heroicons.dev/blob/master/src/state.tsx#L59). Tag search is removed right now for the major refactor.

If you feel I can improve search or have other comments please let me know. Thank you!

**Comment by zaydek** [comment]
Closing this for now as icons are generally separated by major version. If icons get added in steps I’ll consider this.
